sudo: true
language: scala
scala:
  - 2.11.11
  - 2.12.8
  - 2.13.0

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test
